name: loco2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.18.1
  - ampl-asl=1.0.0
  - backports.zstd=1.3.0
  - bcrypt=5.0.0
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=2.2.1
  - cppad=20250000.2
  - cryptography=46.0.3
  - docker-py=6.1.3
  - ecole=0.8.2
  - entrypoints=0.4
  - flask=2.3.3
  - fmt=12.1.0
  - gitdb=4.0.12
  - gitpython=3.1.46
  - gmp=6.3.0
  - greenlet=3.3.0
  - gunicorn=20.1.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - invoke=2.2.1
  - ipopt=3.14.19
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.45
  - libblas=3.11.0
  - libcblas=3.11.0
  - libecole=0.8.2
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libprotobuf=3.20.3
  - libscotch=7.0.4
  - libsodium=1.0.20
  - libspral=2025.05.20
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - mako=1.3.10
  - metis=5.1.0
  - mpfr=4.2.1
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.6.0
  - packaging=21.3
  - paramiko=4.0.0
  - pip=25.3
  - prometheus_client=0.24.1
  - prometheus_flask_exporter=0.23.2
  - pycparser=2.22
  - pynacl=1.6.2
  - pyscipopt=5.6.0
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.3
  - querystring_parser=1.2.4
  - readline=8.3
  - requests=2.32.5
  - scip=9.2.4
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - sqlalchemy=1.4.54
  - sqlparse=0.5.5
  - tbb=2022.3.0
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - urllib3=2.6.3
  - websocket-client=1.9.0
  - werkzeug=3.1.5
  - wheel=0.45.1
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.12.1
    - asttokens==3.0.1
    - async-timeout==5.0.1
    - attrs==25.4.0
    - cachetools==6.2.4
    - cmippy==0.1.dev8+g1ec64f890.d20260129
    - contourpy==1.3.2
    - coptpy==8.0.3
    - cuda-bindings==12.9.4
    - cuda-pathfinder==1.2.2
    - cycler==0.12.1
    - databricks-cli==0.18.0
    - databricks-sdk==0.78.0
    - decorator==5.2.1
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastapi==0.128.0
    - filelock==3.20.0
    - flask-cors==6.0.2
    - fonttools==4.61.1
    - frozenlist==1.8.0
    - fsspec==2025.12.0
    - google-auth==2.47.0
    - graphene==3.4.3
    - graphql-core==3.2.7
    - graphql-relay==3.2.0
    - gurobipy==13.0.0
    - h11==0.16.0
    - huey==2.6.0
    - hydra-core==1.3.2
    - importlib-metadata==8.7.1
    - ipython==8.38.0
    - jedi==0.19.2
    - joblib==1.5.3
    - kiwisolver==1.4.9
    - loco==0.1.dev51+gc32b6e7d4.d20260121
    - markupsafe==2.1.5
    - matplotlib==3.10.8
    - matplotlib-inline==0.2.1
    - mlflow==3.8.1
    - mlflow-skinny==3.8.1
    - mlflow-tracing==3.8.1
    - mpmath==1.3.0
    - multidict==6.7.0
    - networkx==3.4.2
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvshmem-cu12==3.4.5
    - nvidia-nvtx-cu12==12.6.77
    - oauthlib==3.3.1
    - omegaconf==2.3.0
    - opentelemetry-api==1.39.1
    - opentelemetry-proto==1.39.1
    - opentelemetry-sdk==1.39.1
    - opentelemetry-semantic-conventions==0.60b1
    - pandas==2.3.3
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==12.0.0
    - prompt-toolkit==3.0.52
    - propcache==0.4.1
    - protobuf==6.33.4
    - psutil==7.2.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyaml==25.7.0
    - pyarrow==22.0.0
    - pyasn1==0.6.2
    - pyasn1-modules==0.4.2
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pygments==2.19.2
    - pyjwt==2.10.1
    - pyparsing==3.3.1
    - python-dotenv==1.2.1
    - pytz==2025.2
    - rsa==4.9.1
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - stack-data==0.6.3
    - starlette==0.50.0
    - sympy==1.14.0
    - tabulate==0.9.0
    - threadpoolctl==3.6.0
    - torch==2.10.0+cu126
    - torch-geometric==2.7.0
    - torchvision==0.25.0+cu126
    - tqdm==4.67.1
    - tqdm-joblib==0.0.5
    - traitlets==5.14.3
    - triton==3.6.0
    - typing-inspection==0.4.2
    - tzdata==2025.3
    - uvicorn==0.40.0
    - wcwidth==0.3.5
    - xxhash==3.6.0
    - yarl==1.22.0
prefix: /scratch/gpfs/BSTELLATO/stefan/.conda/envs/loco2
